#!/usr/bin/env python3
"""
extract_circuits.py

Fetches F1 circuit layout data from the free OpenF1 REST API and writes:
  - scripts/output/svgs/<circuit_key>.svg   (one per circuit)
  - scripts/output/bounds.json              (all circuit bounds, for backend normalisation)

The SVG track outline is generated by sampling a driver's real position data
over 3 clean laps. Because the outline and the live telemetry come from the
same coordinate system, they are automatically aligned — no manual calibration.

Usage:
  python scripts/extract_circuits.py                   # all 2024 circuits
  python scripts/extract_circuits.py --year 2023
  python scripts/extract_circuits.py --circuit bahrain # single circuit only

Requires: httpx  (already in backend/requirements.txt)
  Activate the backend venv:  source backend/.venv/bin/activate
  Or install directly:        pip install httpx
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import httpx

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

BASE_URL = "https://api.openf1.org/v1"
VIEWBOX = 1000          # SVG coordinate space (0–1000 on both axes)
MAX_PTS = 600           # max points in SVG polyline (enough for smooth curves)
REQUEST_DELAY = 1.0     # seconds between API calls (be kind to the free API)
TIMEOUT = 30.0          # seconds per HTTP request

# Drivers to try in order — if one has no/incomplete data for a circuit, try next
FALLBACK_DRIVERS = [1, 11, 44, 63, 16, 55, 4]

# Target laps: skip lap 1 (formation/standing start) and lap 2 (first-lap chaos)
LAP_START = 3
LAP_END = 6  # exclusive — fetches laps 3, 4, 5

OUTPUT_DIR = Path(__file__).parent / "output"


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def fetch(client: httpx.Client, path: str, params: dict) -> list[dict]:
    """Make a GET request and return the JSON list. Raises on non-2xx."""
    url = f"{BASE_URL}{path}"
    response = client.get(url, params=params, timeout=TIMEOUT)
    response.raise_for_status()
    return response.json()


def get_sessions(client: httpx.Client, year: int) -> list[dict]:
    """Return all Race sessions for the given year, each with a unique circuit_key."""
    print(f"  Fetching sessions for {year}...")
    sessions = fetch(client, "/sessions", {"year": year, "session_name": "Race"})

    # Deduplicate by circuit_key — keep only one session per circuit
    seen: set[str] = set()
    unique = []
    for s in sessions:
        key = s.get("circuit_key")
        if key and key not in seen:
            seen.add(key)
            unique.append(s)

    print(f"  Found {len(unique)} unique circuits")
    return unique


def get_laps(client: httpx.Client, session_key: int, driver_number: int) -> list[dict]:
    """Return all laps for a driver in a session, sorted by lap_number."""
    laps = fetch(client, "/laps", {
        "session_key": session_key,
        "driver_number": driver_number,
    })
    return sorted(laps, key=lambda l: l.get("lap_number", 0))


def get_location(
    client: httpx.Client,
    session_key: int,
    driver_number: int,
    date_start: str,
    date_end: str,
) -> list[dict]:
    """Return position data for a driver between two ISO timestamps."""
    return fetch(client, "/location", {
        "session_key": session_key,
        "driver_number": driver_number,
        f"date>": date_start,
        f"date<": date_end,
    })


# ---------------------------------------------------------------------------
# Data processing
# ---------------------------------------------------------------------------

def clean_and_sample(
    raw: list[dict],
    max_pts: int = MAX_PTS,
) -> list[tuple[float, float]]:
    """
    Extract (x, y) pairs, drop telemetry dropouts, and downsample.

    Dropouts are points where x or y is 0 or None — common in OpenF1 data
    when a car is in the pit lane or when the GPS signal is lost briefly.
    """
    points = [
        (p["x"], p["y"])
        for p in raw
        if p.get("x") and p.get("y")
        and p["x"] != 0 and p["y"] != 0
    ]

    if not points:
        return []

    # Uniform stride downsampling
    if len(points) > max_pts:
        stride = len(points) // max_pts
        points = points[::stride]

    return points


def normalise(
    points: list[tuple[float, float]],
    viewbox: int = VIEWBOX,
) -> tuple[list[tuple[float, float]], dict]:
    """
    Normalise raw metre coordinates into the SVG viewBox with aspect ratio preserved.

    Both axes use the same scale factor (derived from the larger dimension) so the
    circuit shape is not stretched. The result is centred within the viewBox, with
    padding on the shorter sides.

    Y axis is flipped: in OpenF1, higher y = further north; in SVG, higher y = further down.

    Returns (normalised_points, bounds_dict).
    The bounds_dict includes scale/offset values so the backend can apply the same
    formula to live telemetry positions.
    """
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]

    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)

    x_range = x_max - x_min or 1.0
    y_range = y_max - y_min or 1.0

    # Single uniform scale: the larger dimension fills the viewBox exactly.
    # The smaller dimension is proportionally smaller, leaving padding on both sides.
    scale = viewbox / max(x_range, y_range)

    # Centre both axes within the viewBox.
    x_offset = (viewbox - x_range * scale) / 2
    y_offset = (viewbox - y_range * scale) / 2

    normalised = [
        (
            round((x - x_min) * scale + x_offset, 2),
            round((y_max - y) * scale + y_offset, 2),  # flip Y
        )
        for x, y in points
    ]

    bounds = {
        "x_min": round(x_min, 3),
        "x_max": round(x_max, 3),
        "y_min": round(y_min, 3),
        "y_max": round(y_max, 3),
        # Backend uses these to apply the identical normalisation to live positions:
        #   x_svg = (x - x_min) * scale + x_offset
        #   y_svg = (y_max - y) * scale + y_offset
        "scale": round(scale, 6),
        "x_offset": round(x_offset, 3),
        "y_offset": round(y_offset, 3),
    }

    return normalised, bounds


def build_svg(points: list[tuple[float, float]], viewbox: int = VIEWBOX) -> str:
    """Generate an SVG string containing a single polyline for the circuit outline."""
    pts_str = " ".join(f"{x},{y}" for x, y in points)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {viewbox} {viewbox}">\n'
        f'  <polyline\n'
        f'    points="{pts_str}"\n'
        f'    fill="none"\n'
        f'    stroke="#888"\n'
        f'    stroke-width="4"\n'
        f'    stroke-linejoin="round"\n'
        f'    stroke-linecap="round"\n'
        f'  />\n'
        f'</svg>\n'
    )


# ---------------------------------------------------------------------------
# Per-circuit processing
# ---------------------------------------------------------------------------

def process_circuit(
    client: httpx.Client,
    session: dict,
    output_dir: Path,
) -> dict | None:
    """
    Fetch, process, and write the SVG for a single circuit.

    Returns the bounds dict on success, None on failure.
    Skips circuits where the SVG already exists (resume support).
    """
    circuit_key = session["circuit_key"]
    circuit_name = session.get("circuit_short_name", circuit_key)
    session_key = session["session_key"]

    circuit_name_safe = circuit_name.replace(" ", "_")
    svg_path = output_dir / "svgs" / f"{circuit_name_safe}_{circuit_key}.svg"

    if svg_path.exists():
        print(f"  [{circuit_name}] already exists, skipping")
        # Still need to return bounds if we want to rebuild bounds.json
        # Return None and let caller handle it
        return None

    print(f"  [{circuit_name}] session_key={session_key}")

    # Try each fallback driver until we get usable data
    for driver_number in FALLBACK_DRIVERS:
        try:
            laps = get_laps(client, session_key, driver_number)
            time.sleep(0.3)

            # Find the target lap window
            lap_map = {l["lap_number"]: l for l in laps if l.get("date_start")}
            if LAP_START not in lap_map or LAP_END not in lap_map:
                print(f"    Driver {driver_number}: laps {LAP_START}–{LAP_END} not found, trying next")
                continue

            t_start = lap_map[LAP_START]["date_start"]
            t_end = lap_map[LAP_END]["date_start"]

            print(f"    Driver {driver_number}: fetching location {t_start} → {t_end}")
            raw = get_location(client, session_key, driver_number, t_start, t_end)
            time.sleep(0.3)

            points = clean_and_sample(raw)
            if len(points) < 50:
                print(f"    Driver {driver_number}: only {len(points)} points after cleaning, trying next")
                continue

            print(f"    {len(raw)} raw → {len(points)} sampled points")

            normalised, bounds = normalise(points)
            svg = build_svg(normalised)

            svg_path.parent.mkdir(parents=True, exist_ok=True)
            svg_path.write_text(svg)
            print(f"    Written: {svg_path}")

            return {
                "circuit_short_name": circuit_name,
                "session_key": session_key,
                **bounds,
            }

        except httpx.HTTPStatusError as e:
            print(f"    Driver {driver_number}: HTTP {e.response.status_code}, trying next")
            time.sleep(1.0)
        except Exception as e:
            print(f"    Driver {driver_number}: error — {e}, trying next")
            time.sleep(1.0)

    print(f"  [{circuit_name}] FAILED — no usable data from any driver")
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Extract F1 circuit SVGs from OpenF1")
    parser.add_argument("--year", type=int, default=2024, help="F1 season year (default: 2024)")
    parser.add_argument("--circuit", type=str, default=None, help="Process a single circuit_key only")
    args = parser.parse_args()

    output_dir = OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "svgs").mkdir(exist_ok=True)

    bounds_path = output_dir / "bounds.json"

    # Load existing bounds so we can merge (supports incremental runs)
    all_bounds: dict = {}
    if bounds_path.exists():
        all_bounds = json.loads(bounds_path.read_text())

    print(f"RaceTime circuit extractor — year={args.year}")
    print(f"Output: {output_dir.resolve()}\n")

    with httpx.Client() as client:
        sessions = get_sessions(client, args.year)

        if args.circuit:
            sessions = [s for s in sessions if s.get("circuit_key") == args.circuit]
            if not sessions:
                print(f"Circuit '{args.circuit}' not found in {args.year} season.")
                return

        for i, session in enumerate(sessions, 1):
            circuit_key = session["circuit_key"]
            print(f"\n[{i}/{len(sessions)}] {circuit_key}")

            result = process_circuit(client, session, output_dir)

            if result is not None:
                all_bounds[circuit_key] = result
                # Write bounds after each circuit so progress is not lost
                bounds_path.write_text(json.dumps(all_bounds, indent=2))
                print(f"    bounds.json updated")

            if i < len(sessions):
                time.sleep(REQUEST_DELAY)

    print(f"\nDone. {len(all_bounds)} circuits in bounds.json")
    print(f"SVGs: {output_dir / 'svgs'}")
    print(f"Bounds: {bounds_path}")


if __name__ == "__main__":
    main()
